# Generated by Django 5.2.17 on 2026-09-19 09:10

import apps.listings.models
import apps.listings.schema
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='nombre en inglés')),
                ('fields_schema', models.JSONField(default=apps.listings.schema.empty_schema, help_text='JSON Schema (tipo object) con los campos propios de la categoría.', validators=[apps.listings.schema.validate_fields_schema], verbose_name='campos extra')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(max_length=4000, verbose_name='descripción')),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('like_new', 'Como nuevo'), ('good', 'Buen estado'), ('fair', 'Con detalles'), ('for_parts', 'Para repuestos')], max_length=10, verbose_name='estado del artículo')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='campos de la categoría')),
                ('city', models.CharField(max_length=80, verbose_name='ciudad')),
                ('pickup_address', models.CharField(max_length=200, verbose_name='dirección de recogida')),
                ('is_original', models.BooleanField(default=True, verbose_name='¿es original?')),
                ('terms_accepted_at', models.DateTimeField(verbose_name='términos aceptados')),
                ('status', models.CharField(choices=[('in_review', 'En revisión'), ('offered', 'Con oferta'), ('accepted', 'Aceptada'), ('pickup_sent', 'Recogida enviada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], db_index=True, default='in_review', max_length=12, verbose_name='estado')),
                ('status_changed_at', models.DateTimeField(auto_now_add=True, verbose_name='último cambio de estado')),
                ('offer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='oferta')),
                ('offer_currency', models.CharField(blank=True, max_length=3, verbose_name='moneda')),
                ('pickup_by', models.CharField(blank=True, choices=[('seller', 'El vendedor lo envía'), ('platform', 'Trueke lo recoge')], max_length=10, verbose_name='responsable de la recogida')),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='fecha de recogida')),
                ('pickup_notes', models.CharField(blank=True, max_length=500, verbose_name='indicaciones de recogida')),
                ('cancel_reason', models.CharField(blank=True, max_length=500, verbose_name='motivo de cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.category', verbose_name='categoría')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
            ],
            options={
                'verbose_name': 'publicación',
                'verbose_name_plural': 'publicaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20, verbose_name='acción')),
                ('from_status', models.CharField(blank=True, choices=[('in_review', 'En revisión'), ('offered', 'Con oferta'), ('accepted', 'Aceptada'), ('pickup_sent', 'Recogida enviada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], max_length=12)),
                ('to_status', models.CharField(choices=[('in_review', 'En revisión'), ('offered', 'Con oferta'), ('accepted', 'Aceptada'), ('pickup_sent', 'Recogida enviada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], max_length=12)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_events', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='listings.listing')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.listings.models.listing_image_path, validators=[apps.listings.models.validate_listing_image], verbose_name='imagen')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imágenes',
                'ordering': ['position', 'id'],
            },
        ),
    ]
