# Generated by Django 5.2.17 on 2026-09-19 14:51

import apps.accounts.files
import apps.listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='monto pagado'),
        ),
        migrations.AddField(
            model_name='listing',
            name='paid_at',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de pago'),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_receipt',
            field=models.FileField(blank=True, storage=apps.accounts.files.private_storage, upload_to=apps.listings.models.listing_receipt_path, validators=[apps.accounts.files.validate_private_file], verbose_name='comprobante de pago'),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=80, verbose_name='referencia del pago'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('in_review', 'En revisión'), ('offered', 'Con oferta'), ('accepted', 'Aceptada'), ('pickup_sent', 'Recogida enviada'), ('completed', 'Completada'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], db_index=True, default='in_review', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='listingevent',
            name='from_status',
            field=models.CharField(blank=True, choices=[('in_review', 'En revisión'), ('offered', 'Con oferta'), ('accepted', 'Aceptada'), ('pickup_sent', 'Recogida enviada'), ('completed', 'Completada'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], max_length=12),
        ),
        migrations.AlterField(
            model_name='listingevent',
            name='to_status',
            field=models.CharField(choices=[('in_review', 'En revisión'), ('offered', 'Con oferta'), ('accepted', 'Aceptada'), ('pickup_sent', 'Recogida enviada'), ('completed', 'Completada'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], max_length=12),
        ),
    ]
