# Generated by Django 5.2.17 on 2026-09-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='counter_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='contraoferta'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('in_review', 'En revisión'), ('offered', 'Con oferta'), ('countered', 'Contraoferta'), ('accepted', 'Aceptada'), ('pickup_sent', 'Recogida enviada'), ('completed', 'Completada'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], db_index=True, default='in_review', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='listingevent',
            name='from_status',
            field=models.CharField(blank=True, choices=[('in_review', 'En revisión'), ('offered', 'Con oferta'), ('countered', 'Contraoferta'), ('accepted', 'Aceptada'), ('pickup_sent', 'Recogida enviada'), ('completed', 'Completada'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], max_length=12),
        ),
        migrations.AlterField(
            model_name='listingevent',
            name='to_status',
            field=models.CharField(choices=[('in_review', 'En revisión'), ('offered', 'Con oferta'), ('countered', 'Contraoferta'), ('accepted', 'Aceptada'), ('pickup_sent', 'Recogida enviada'), ('completed', 'Completada'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], max_length=12),
        ),
    ]
