# Generated by Django 5.2.17 on 2026-09-19 15:09

import apps.listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_counter_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=apps.listings.models.listing_image_path, verbose_name='miniatura'),
        ),
    ]
