# Generated by Django 5.2.17 on 2026-09-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='último recordatorio'),
        ),
    ]
