# Generated by Django 5.2.17 on 2026-09-19 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('listing.create', 'Nueva publicación'), ('listing.offer', 'Nueva oferta'), ('listing.accept', 'Oferta aceptada'), ('listing.reject', 'Oferta rechazada'), ('listing.pickup', 'Recogida coordinada'), ('listing.complete', 'Venta completada'), ('listing.cancel', 'Publicación cancelada'), ('message.new', 'Mensajes nuevos')], max_length=20, verbose_name='tipo')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='vista')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'seen_at'], name='notificatio_user_id_1c048e_idx')],
            },
        ),
    ]
