# Generated by Django 5.2.17 on 2026-09-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('listing.create', 'Nueva publicación'), ('listing.offer', 'Nueva oferta'), ('listing.accept', 'Oferta aceptada'), ('listing.reject', 'Oferta rechazada'), ('listing.pickup', 'Recogida coordinada'), ('listing.complete', 'Venta completada'), ('listing.pay', 'Pago registrado'), ('listing.cancel', 'Publicación cancelada'), ('message.new', 'Mensajes nuevos')], max_length=20, verbose_name='tipo'),
        ),
    ]
