/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/otp/request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Envía un código de acceso al teléfono. */
        post: operations["auth_otp_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Verifica el código. Si el teléfono no tiene cuenta, la crea. */
        post: operations["auth_otp_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Categorías activas con su esquema de campos extra. Pública (la usa la landing). */
        get: operations["categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listings_list"];
        put?: never;
        post: operations["listings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{listing_id}/messages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mensajes de la publicación, del más nuevo al más viejo. Enviar: JSON o multipart con adjunto. */
        get: operations["listings_messages_list"];
        put?: never;
        /** @description Mensajes de la publicación, del más nuevo al más viejo. Enviar: JSON o multipart con adjunto. */
        post: operations["listings_messages_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{listing_id}/messages/{id}/attachment/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listings_messages_attachment_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{listing_id}/messages/read/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Marca como leídos los mensajes del otro lado. */
        post: operations["listings_messages_read_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["listings_partial_update"];
        trace?: never;
    };
    "/api/listings/{id}/accept/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listings_accept_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listings_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listings_complete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listings_events_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/images/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listings_images_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/images/{image_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["listings_images_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/offer/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listings_offer_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/pickup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listings_pickup_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/reject/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listings_reject_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Cuántas publicaciones hay en cada estado (pestañas del panel). */
        get: operations["listings_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["me_partial_update"];
        trace?: never;
    };
    "/api/me/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Sube el documento de identidad y/o el certificado bancario (multipart). */
        patch: operations["me_documents_partial_update"];
        trace?: never;
    };
    "/api/me/documents/{kind}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_documents_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/newsletter/subscribe/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Suscribe un email. Responde igual exista o no, para no revelar quién está suscrito. */
        post: operations["newsletter_subscribe_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/newsletter/unsubscribe/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["newsletter_unsubscribe_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notifications_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/seen/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["notifications_seen_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/seen-all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Marca todas como vistas (la campana). */
        post: operations["notifications_seen_all_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/unseen-count/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notifications_unseen_count_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Perfil completo de un usuario, para que el operador lo verifique y le pague. Solo operadores. */
        get: operations["users_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/documents/{kind}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_documents_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResponse: {
            access: string;
            refresh: string;
            created: boolean;
            user: components["schemas"]["User"];
        };
        /**
         * @description * `offer` - offer
         *     * `accept` - accept
         *     * `reject` - reject
         *     * `pickup` - pickup
         *     * `complete` - complete
         *     * `cancel` - cancel
         * @enum {string}
         */
        AvailableActionsEnum: "offer" | "accept" | "reject" | "pickup" | "complete" | "cancel";
        /** @enum {unknown} */
        BlankEnum: "";
        Category: {
            readonly id: number;
            /** Código */
            code: string;
            name: string;
            /**
             * Campos extra
             * @description JSON Schema (tipo object) con los campos propios de la categoría.
             */
            fields_schema?: unknown;
        };
        /**
         * @description * `new` - Nuevo
         *     * `like_new` - Como nuevo
         *     * `good` - Buen estado
         *     * `fair` - Con detalles
         *     * `for_parts` - Para repuestos
         * @enum {string}
         */
        ConditionEnum: "new" | "like_new" | "good" | "fair" | "for_parts";
        /**
         * @description * `national_id` - Documento nacional
         *     * `foreign_id` - Documento de extranjería
         *     * `passport` - Pasaporte
         * @enum {string}
         */
        DocumentTypeEnum: "national_id" | "foreign_id" | "passport";
        /**
         * @description * `listing.create` - Nueva publicación
         *     * `listing.offer` - Nueva oferta
         *     * `listing.accept` - Oferta aceptada
         *     * `listing.reject` - Oferta rechazada
         *     * `listing.pickup` - Recogida coordinada
         *     * `listing.complete` - Venta completada
         *     * `listing.cancel` - Publicación cancelada
         *     * `message.new` - Mensajes nuevos
         * @enum {string}
         */
        KindEnum: "listing.create" | "listing.offer" | "listing.accept" | "listing.reject" | "listing.pickup" | "listing.complete" | "listing.cancel" | "message.new";
        /**
         * @description * `es` - Español
         *     * `en` - English
         * @enum {string}
         */
        LanguageEnum: "es" | "en";
        Listing: {
            readonly id: number;
            readonly seller: components["schemas"]["Seller"];
            category: number;
            /** Nombre */
            title: string;
            /** Descripción */
            description: string;
            /** Estado del artículo */
            condition: components["schemas"]["ConditionEnum"];
            /** Campos de la categoría */
            attributes?: unknown;
            /** Ciudad */
            city: string;
            /** Dirección de recogida */
            pickup_address: string;
            /** ¿es original? */
            is_original?: boolean;
            terms_accepted?: boolean;
            /**
             * Términos aceptados
             * Format: date-time
             */
            readonly terms_accepted_at: string;
            readonly images: components["schemas"]["ListingImage"][];
            /** Estado */
            readonly status: components["schemas"]["ListingStatusEnum"];
            /**
             * Último cambio de estado
             * Format: date-time
             */
            readonly status_changed_at: string;
            /**
             * Oferta
             * Format: decimal
             */
            readonly offer_amount: string | null;
            /** Moneda */
            readonly offer_currency: string;
            /** Responsable de la recogida */
            readonly pickup_by: components["schemas"]["PickupByEnum"];
            /**
             * Fecha de recogida
             * Format: date
             */
            readonly pickup_date: string | null;
            /** Indicaciones de recogida */
            readonly pickup_notes: string;
            /** Motivo de cancelación */
            readonly cancel_reason: string;
            readonly available_actions: components["schemas"]["AvailableActionsEnum"][];
            readonly unread_messages: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ListingEvent: {
            readonly id: number;
            /** Acción */
            action: string;
            from_status?: components["schemas"]["ListingStatusEnum"] | components["schemas"]["BlankEnum"];
            to_status: components["schemas"]["ListingStatusEnum"];
            readonly actor: components["schemas"]["Seller"];
            data?: unknown;
            /** Format: date-time */
            readonly created_at: string;
        };
        ListingImage: {
            readonly id: number;
            /**
             * Imagen
             * Format: uri
             */
            image: string;
            /**
             * Orden
             * Format: int64
             */
            position?: number;
        };
        ListingStats: {
            in_review: number;
            offered: number;
            accepted: number;
            pickup_sent: number;
            completed: number;
            cancelled: number;
        };
        /**
         * @description * `in_review` - En revisión
         *     * `offered` - Con oferta
         *     * `accepted` - Aceptada
         *     * `pickup_sent` - Recogida enviada
         *     * `completed` - Completada
         *     * `cancelled` - Cancelada
         * @enum {string}
         */
        ListingStatusEnum: "in_review" | "offered" | "accepted" | "pickup_sent" | "completed" | "cancelled";
        MarkRead: {
            updated: number;
        };
        Message: {
            readonly id: number;
            readonly listing: number;
            readonly sender: {
                [key: string]: unknown;
            } | null;
            /** Enviado por la plataforma */
            readonly from_platform: boolean;
            /** Texto */
            text?: string;
            /**
             * Adjunto
             * Format: uri
             */
            attachment?: string | null;
            /** @description `pdf` o `image`; el nombre original no se guarda (puede tener datos personales). */
            readonly attachment_kind: string;
            readonly attachment_url: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /**
             * Leído
             * Format: date-time
             */
            readonly read_at: string | null;
        };
        Notification: {
            readonly id: number;
            /** Tipo */
            kind: components["schemas"]["KindEnum"];
            readonly listing: {
                [key: string]: unknown;
            } | null;
            readonly actor: {
                [key: string]: unknown;
            } | null;
            data?: unknown;
            /** Format: date-time */
            created_at: string;
            /**
             * Vista
             * Format: date-time
             */
            seen_at?: string | null;
        };
        NotificationCount: {
            count: number;
        };
        NotificationsSeen: {
            updated: number;
        };
        OtpIssued: {
            expires_in: number;
            resend_in: number;
        };
        OtpRequest: {
            phone: string;
        };
        OtpResendTooSoon: {
            code: string;
            detail: string;
            wait: number;
        };
        OtpVerify: {
            phone: string;
            code: string;
        };
        PaginatedListingEventList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ListingEvent"][];
        };
        PaginatedListingList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Listing"][];
        };
        PaginatedMessageList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Message"][];
        };
        PaginatedNotificationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Notification"][];
        };
        PatchedDocuments: {
            /**
             * Documento
             * Format: uri
             */
            document_file?: string | null;
            /**
             * Certificado bancario
             * Format: uri
             */
            bank_certificate?: string | null;
        };
        PatchedListing: {
            readonly id?: number;
            readonly seller?: components["schemas"]["Seller"];
            category?: number;
            /** Nombre */
            title?: string;
            /** Descripción */
            description?: string;
            /** Estado del artículo */
            condition?: components["schemas"]["ConditionEnum"];
            /** Campos de la categoría */
            attributes?: unknown;
            /** Ciudad */
            city?: string;
            /** Dirección de recogida */
            pickup_address?: string;
            /** ¿es original? */
            is_original?: boolean;
            terms_accepted?: boolean;
            /**
             * Términos aceptados
             * Format: date-time
             */
            readonly terms_accepted_at?: string;
            readonly images?: components["schemas"]["ListingImage"][];
            /** Estado */
            readonly status?: components["schemas"]["ListingStatusEnum"];
            /**
             * Último cambio de estado
             * Format: date-time
             */
            readonly status_changed_at?: string;
            /**
             * Oferta
             * Format: decimal
             */
            readonly offer_amount?: string | null;
            /** Moneda */
            readonly offer_currency?: string;
            /** Responsable de la recogida */
            readonly pickup_by?: components["schemas"]["PickupByEnum"];
            /**
             * Fecha de recogida
             * Format: date
             */
            readonly pickup_date?: string | null;
            /** Indicaciones de recogida */
            readonly pickup_notes?: string;
            /** Motivo de cancelación */
            readonly cancel_reason?: string;
            readonly available_actions?: components["schemas"]["AvailableActionsEnum"][];
            readonly unread_messages?: number;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedUser: {
            readonly id?: number;
            /** Teléfono */
            readonly phone?: string;
            /** Nombre */
            first_name?: string;
            /** Apellido */
            last_name?: string;
            email?: string;
            /**
             * Foto
             * Format: uri
             */
            photo?: string | null;
            /** Idioma */
            language?: components["schemas"]["LanguageEnum"];
            /** Rol */
            readonly role?: components["schemas"]["RoleEnum"];
            /** Tipo de documento */
            document_type?: components["schemas"]["DocumentTypeEnum"] | components["schemas"]["BlankEnum"];
            /** Número de documento */
            document_number?: string;
            readonly has_document_file?: boolean;
            readonly has_bank_certificate?: boolean;
            /** @description Datos mínimos para que la plataforma pueda pagarle al vendedor. */
            readonly profile_complete?: boolean;
            /** Format: date-time */
            readonly date_joined?: string;
        };
        /**
         * @description * `seller` - El vendedor lo envía
         *     * `platform` - Trueke lo recoge
         * @enum {string}
         */
        PickupByEnum: "seller" | "platform";
        /**
         * @description * `seller` - Vendedor
         *     * `operator` - Operador
         * @enum {string}
         */
        RoleEnum: "seller" | "operator";
        Seller: {
            id: number;
            name: string;
        };
        Subscribe: {
            /** Format: email */
            email: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        Unsubscribe: {
            /** Format: uuid */
            token: string;
        };
        User: {
            readonly id: number;
            /** Teléfono */
            readonly phone: string;
            /** Nombre */
            first_name?: string;
            /** Apellido */
            last_name?: string;
            email?: string;
            /**
             * Foto
             * Format: uri
             */
            photo?: string | null;
            /** Idioma */
            language?: components["schemas"]["LanguageEnum"];
            /** Rol */
            readonly role: components["schemas"]["RoleEnum"];
            /** Tipo de documento */
            document_type?: components["schemas"]["DocumentTypeEnum"] | components["schemas"]["BlankEnum"];
            /** Número de documento */
            document_number?: string;
            readonly has_document_file: boolean;
            readonly has_bank_certificate: boolean;
            /** @description Datos mínimos para que la plataforma pueda pagarle al vendedor. */
            readonly profile_complete: boolean;
            /** Format: date-time */
            readonly date_joined: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_otp_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OtpRequest"];
                "multipart/form-data": components["schemas"]["OtpRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpIssued"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpResendTooSoon"];
                };
            };
        };
    };
    auth_otp_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerify"];
                "application/x-www-form-urlencoded": components["schemas"]["OtpVerify"];
                "multipart/form-data": components["schemas"]["OtpVerify"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    listings_list: {
        parameters: {
            query?: {
                /** @description Código de la categoría */
                category?: string;
                city?: string;
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Busca en nombre, descripción y vendedor */
                q?: string;
                /** @description Uno o varios estados separados por coma */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListingList"];
                };
            };
        };
    };
    listings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Listing"];
                "application/x-www-form-urlencoded": components["schemas"]["Listing"];
                "multipart/form-data": components["schemas"]["Listing"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_messages_list: {
        parameters: {
            query?: {
                /** @description El valor del cursor de paginación. */
                cursor?: string;
            };
            header?: never;
            path: {
                listing_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMessageList"];
                };
            };
        };
    };
    listings_messages_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Message"];
                "multipart/form-data": components["schemas"]["Message"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    listings_messages_attachment_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                listing_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archivo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listings_messages_read_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkRead"];
                };
            };
        };
    };
    listings_retrieve: {
        parameters: {
            query?: {
                /** @description Código de la categoría */
                category?: string;
                city?: string;
                /** @description Busca en nombre, descripción y vendedor */
                q?: string;
                /** @description Uno o varios estados separados por coma */
                status?: string;
            };
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este publicación. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este publicación. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedListing"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedListing"];
                "multipart/form-data": components["schemas"]["PatchedListing"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_accept_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este publicación. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Listing"];
                "application/x-www-form-urlencoded": components["schemas"]["Listing"];
                "multipart/form-data": components["schemas"]["Listing"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este publicación. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Listing"];
                "application/x-www-form-urlencoded": components["schemas"]["Listing"];
                "multipart/form-data": components["schemas"]["Listing"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_complete_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este publicación. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Listing"];
                "application/x-www-form-urlencoded": components["schemas"]["Listing"];
                "multipart/form-data": components["schemas"]["Listing"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_events_list: {
        parameters: {
            query?: {
                /** @description Código de la categoría */
                category?: string;
                city?: string;
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Busca en nombre, descripción y vendedor */
                q?: string;
                /** @description Uno o varios estados separados por coma */
                status?: string;
            };
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este publicación. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListingEventList"];
                };
            };
        };
    };
    listings_images_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este publicación. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ListingImage"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingImage"];
                };
            };
        };
    };
    listings_images_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este publicación. */
                id: number;
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listings_offer_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este publicación. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Listing"];
                "application/x-www-form-urlencoded": components["schemas"]["Listing"];
                "multipart/form-data": components["schemas"]["Listing"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_pickup_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este publicación. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Listing"];
                "application/x-www-form-urlencoded": components["schemas"]["Listing"];
                "multipart/form-data": components["schemas"]["Listing"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_reject_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este publicación. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Listing"];
                "application/x-www-form-urlencoded": components["schemas"]["Listing"];
                "multipart/form-data": components["schemas"]["Listing"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_stats_retrieve: {
        parameters: {
            query?: {
                /** @description Código de la categoría */
                category?: string;
                city?: string;
                /** @description Busca en nombre, descripción y vendedor */
                q?: string;
                /** @description Uno o varios estados separados por coma */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingStats"];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
                "multipart/form-data": components["schemas"]["PatchedUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    me_documents_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedDocuments"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    me_documents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archivo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    newsletter_subscribe_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Subscribe"];
                "application/x-www-form-urlencoded": components["schemas"]["Subscribe"];
                "multipart/form-data": components["schemas"]["Subscribe"];
            };
        };
        responses: {
            /** @description Recibido */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    newsletter_unsubscribe_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Unsubscribe"];
                "application/x-www-form-urlencoded": components["schemas"]["Unsubscribe"];
                "multipart/form-data": components["schemas"]["Unsubscribe"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    notifications_list: {
        parameters: {
            query?: {
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Solo las no vistas */
                unseen?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNotificationList"];
                };
            };
        };
    };
    notifications_seen_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este notificación. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsSeen"];
                };
            };
        };
    };
    notifications_seen_all_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsSeen"];
                };
            };
        };
    };
    notifications_unseen_count_retrieve: {
        parameters: {
            query?: {
                /** @description Solo las no vistas */
                unseen?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationCount"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_documents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archivo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
