/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/otp/request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Envía un código de acceso al teléfono. */
        post: operations["auth_otp_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Verifica el código. Si el teléfono no tiene cuenta, la crea. */
        post: operations["auth_otp_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Categorías activas con su esquema de campos extra. Pública (la usa la landing). */
        get: operations["categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listings_list"];
        put?: never;
        post: operations["listings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{listing_id}/messages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mensajes de la publicación, del más nuevo al más viejo. Enviar: JSON o multipart con adjunto. */
        get: operations["listings_messages_list"];
        put?: never;
        /** @description Mensajes de la publicación, del más nuevo al más viejo. Enviar: JSON o multipart con adjunto. */
        post: operations["listings_messages_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{listing_id}/messages/{id}/attachment/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listings_messages_attachment_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{listing_id}/messages/read/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Marca como leídos los mensajes del otro lado. */
        post: operations["listings_messages_read_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["listings_partial_update"];
        trace?: never;
    };
    "/api/listings/{id}/accept/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept offer */
        post: operations["listings_accept_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/accept-counter/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept counteroffer */
        post: operations["listings_accept_counter_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["listings_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete sale */
        post: operations["listings_complete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/counter/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Make a counteroffer */
        post: operations["listings_counter_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listings_events_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/images/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listings_images_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/images/{image_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["listings_images_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/offer/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Make an offer */
        post: operations["listings_offer_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/pay/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record payment */
        post: operations["listings_pay_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/pickup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Arrange pickup */
        post: operations["listings_pickup_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/receipt/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Comprobante de pago: lo ven el vendedor y los operadores. */
        get: operations["listings_receipt_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/reject/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline offer */
        post: operations["listings_reject_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Números del panel del operador
         * @description Colas de trabajo, embudo y números de los últimos 30 días.
         */
        get: operations["listings_dashboard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/offers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Tabla de ofertas: una fila por publicación, con las fechas de cada paso. */
        get: operations["listings_offers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/offers/export/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description La misma tabla, en CSV, sin paginar. */
        get: operations["listings_offers_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Cuántas publicaciones hay en cada estado (pestañas del panel). */
        get: operations["listings_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resumen del vendedor
         * @description Cuánto ha ganado, cuánto le falta cobrar y cuántas publicaciones tiene en curso.
         */
        get: operations["listings_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["me_partial_update"];
        trace?: never;
    };
    "/api/me/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Sube el documento de identidad y/o el certificado bancario (multipart). */
        patch: operations["me_documents_partial_update"];
        trace?: never;
    };
    "/api/me/documents/{kind}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_documents_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/newsletter/subscribe/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Suscribe un email. Responde igual exista o no, para no revelar quién está suscrito. */
        post: operations["newsletter_subscribe_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/newsletter/unsubscribe/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["newsletter_unsubscribe_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notifications_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/seen/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["notifications_seen_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/seen-all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Marca todas como vistas (la campana). */
        post: operations["notifications_seen_all_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/unseen-count/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notifications_unseen_count_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Perfil completo de un usuario, para que el operador lo verifique y le pague. Solo operadores. */
        get: operations["users_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/documents/{kind}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_documents_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResponse: {
            access: string;
            refresh: string;
            created: boolean;
            user: components["schemas"]["User"];
        };
        /**
         * @description * `offer` - offer
         *     * `accept` - accept
         *     * `counter` - counter
         *     * `accept_counter` - accept_counter
         *     * `reject` - reject
         *     * `pickup` - pickup
         *     * `complete` - complete
         *     * `pay` - pay
         *     * `cancel` - cancel
         * @enum {string}
         */
        AvailableActionsEnum: "offer" | "accept" | "counter" | "accept_counter" | "reject" | "pickup" | "complete" | "pay" | "cancel";
        /** @enum {unknown} */
        BlankEnum: "";
        Category: {
            readonly id: number;
            code: string;
            name: string;
            /**
             * Extra fields
             * @description JSON Schema (object type) with the fields specific to the category.
             */
            fields_schema?: unknown;
        };
        /**
         * @description * `new` - New
         *     * `like_new` - Like new
         *     * `good` - Good condition
         *     * `fair` - Some wear
         *     * `for_parts` - For parts
         * @enum {string}
         */
        ConditionEnum: "new" | "like_new" | "good" | "fair" | "for_parts";
        CounterRequest: {
            /** Format: decimal */
            amount: string;
        };
        Dashboard: {
            days: number;
            queue: components["schemas"]["Queue"];
            funnel: components["schemas"]["Funnel"];
            period: components["schemas"]["Period"];
        };
        /**
         * @description * `national_id` - National ID
         *     * `foreign_id` - Foreign ID
         *     * `passport` - Passport
         * @enum {string}
         */
        DocumentTypeEnum: "national_id" | "foreign_id" | "passport";
        /** @description De las publicaciones creadas en la ventana, cuántas llegaron a cada paso. */
        Funnel: {
            created: number;
            offered: number;
            accepted: number;
            picked_up: number;
            completed: number;
            paid: number;
        };
        /**
         * @description * `listing.create` - New listing
         *     * `listing.offer` - New offer
         *     * `listing.accept` - Offer accepted
         *     * `listing.reject` - Offer declined
         *     * `listing.counter` - Counteroffer
         *     * `listing.accept_counter` - Counteroffer accepted
         *     * `listing.pickup` - Pickup arranged
         *     * `listing.complete` - Sale completed
         *     * `listing.pay` - Payment recorded
         *     * `listing.cancel` - Listing cancelled
         *     * `listing.expire` - Offer expired
         *     * `listing.review_reminder` - Listing waiting for an offer
         *     * `listing.offer_reminder` - Offer with no answer
         *     * `message.new` - New messages
         * @enum {string}
         */
        KindEnum: "listing.create" | "listing.offer" | "listing.accept" | "listing.reject" | "listing.counter" | "listing.accept_counter" | "listing.pickup" | "listing.complete" | "listing.pay" | "listing.cancel" | "listing.expire" | "listing.review_reminder" | "listing.offer_reminder" | "message.new";
        /**
         * @description * `es` - Español
         *     * `en` - English
         * @enum {string}
         */
        LanguageEnum: "es" | "en";
        Listing: {
            readonly id: number;
            readonly seller: components["schemas"]["Seller"];
            category: number;
            /** Name */
            title: string;
            description: string;
            condition: components["schemas"]["ConditionEnum"];
            /** Category fields */
            attributes?: unknown;
            city: string;
            pickup_address: string;
            /** Original? */
            is_original?: boolean;
            /**
             * Terms accepted
             * Format: date-time
             */
            readonly terms_accepted_at: string;
            readonly images: components["schemas"]["ListingImage"][];
            readonly status: components["schemas"]["ListingStatusEnum"];
            /**
             * Last status change
             * Format: date-time
             */
            readonly status_changed_at: string;
            /**
             * Offer
             * Format: decimal
             */
            readonly offer_amount: string | null;
            /** Currency */
            readonly offer_currency: string;
            /**
             * Counteroffer
             * Format: decimal
             */
            readonly counter_amount: string | null;
            readonly counters_left: number;
            /** Pickup handled by */
            readonly pickup_by: components["schemas"]["ListingPickupByEnum"];
            /** Format: date */
            readonly pickup_date: string | null;
            /** Pickup instructions */
            readonly pickup_notes: string;
            /** Cancellation reason */
            readonly cancel_reason: string;
            /**
             * Amount paid
             * Format: decimal
             */
            readonly paid_amount: string | null;
            /**
             * Payment date
             * Format: date
             */
            readonly paid_at: string | null;
            readonly payment_reference: string;
            readonly has_payment_receipt: boolean;
            readonly available_actions: components["schemas"]["AvailableActionsEnum"][];
            readonly unread_messages: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ListingEvent: {
            readonly id: number;
            action: string;
            from_status?: components["schemas"]["ListingStatusEnum"] | components["schemas"]["BlankEnum"];
            to_status: components["schemas"]["ListingStatusEnum"];
            readonly actor: components["schemas"]["Seller"];
            data?: unknown;
            /** Format: date-time */
            readonly created_at: string;
        };
        ListingImage: {
            readonly id: number;
            /** Format: uri */
            image: string;
            /** Format: uri */
            readonly thumbnail: string;
            /**
             * Order
             * Format: int64
             */
            position?: number;
        };
        ListingImageRequest: {
            /** Format: binary */
            image: string;
            /**
             * Order
             * Format: int64
             */
            position?: number;
        };
        /**
         * @description * `seller` - The seller ships it
         *     * `platform` - Trueke picks it up
         * @enum {string}
         */
        ListingPickupByEnum: "seller" | "platform";
        ListingRequest: {
            category: number;
            /** Name */
            title: string;
            description: string;
            condition: components["schemas"]["ConditionEnum"];
            /** Category fields */
            attributes?: unknown;
            city: string;
            pickup_address: string;
            /** Original? */
            is_original?: boolean;
            terms_accepted?: boolean;
        };
        ListingStats: {
            in_review: number;
            offered: number;
            countered: number;
            accepted: number;
            pickup_sent: number;
            completed: number;
            paid: number;
            cancelled: number;
        };
        /**
         * @description * `in_review` - In review
         *     * `offered` - Offer made
         *     * `countered` - Counteroffer
         *     * `accepted` - Accepted
         *     * `pickup_sent` - Pickup scheduled
         *     * `completed` - Completed
         *     * `paid` - Paid
         *     * `cancelled` - Cancelled
         * @enum {string}
         */
        ListingStatusEnum: "in_review" | "offered" | "countered" | "accepted" | "pickup_sent" | "completed" | "paid" | "cancelled";
        MarkRead: {
            updated: number;
        };
        Message: {
            readonly id: number;
            readonly listing: number;
            readonly sender: components["schemas"]["Seller"] | null;
            /** Sent by the platform */
            readonly from_platform: boolean;
            text?: string;
            /** @description `pdf` o `image`; el nombre original no se guarda (puede tener datos personales). */
            readonly attachment_kind: string;
            readonly attachment_url: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /**
             * Read
             * Format: date-time
             */
            readonly read_at: string | null;
        };
        MessageRequest: {
            text?: string;
            /** Format: binary */
            attachment?: string;
        };
        Notification: {
            readonly id: number;
            /** Type */
            kind: components["schemas"]["KindEnum"];
            readonly listing: components["schemas"]["NotificationListing"] | null;
            readonly actor: components["schemas"]["Seller"] | null;
            data?: unknown;
            /** Format: date-time */
            created_at: string;
            /**
             * Seen
             * Format: date-time
             */
            seen_at?: string | null;
        };
        NotificationCount: {
            count: number;
        };
        NotificationListing: {
            id: number;
            title: string;
            status: components["schemas"]["NotificationListingStatusEnum"];
        };
        /**
         * @description * `in_review` - in_review
         *     * `offered` - offered
         *     * `countered` - countered
         *     * `accepted` - accepted
         *     * `pickup_sent` - pickup_sent
         *     * `completed` - completed
         *     * `paid` - paid
         *     * `cancelled` - cancelled
         * @enum {string}
         */
        NotificationListingStatusEnum: "in_review" | "offered" | "countered" | "accepted" | "pickup_sent" | "completed" | "paid" | "cancelled";
        NotificationsSeen: {
            updated: number;
        };
        OfferRequest: {
            /** Format: decimal */
            amount: string;
            /** @default COP */
            currency: string;
        };
        /** @description Una fila de la tabla de ofertas del operador. */
        OfferRow: {
            readonly id: number;
            /** Name */
            readonly title: string;
            readonly seller: components["schemas"]["Seller"];
            readonly category: string;
            readonly city: string;
            readonly status: components["schemas"]["ListingStatusEnum"];
            /**
             * Offer
             * Format: decimal
             */
            readonly offer_amount: string | null;
            /**
             * Counteroffer
             * Format: decimal
             */
            readonly counter_amount: string | null;
            /**
             * Amount paid
             * Format: decimal
             */
            readonly paid_amount: string | null;
            /** Currency */
            readonly offer_currency: string;
            readonly payment_reference: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly offered_at: string;
            /** Format: date-time */
            readonly accepted_at: string;
            /**
             * Payment date
             * Format: date
             */
            readonly paid_at: string | null;
        };
        OtpIssued: {
            expires_in: number;
            resend_in: number;
        };
        OtpRequestRequest: {
            phone: string;
        };
        OtpResendTooSoon: {
            code: string;
            detail: string;
            wait: number;
        };
        OtpVerifyRequest: {
            phone: string;
            code: string;
        };
        PaginatedListingList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Listing"][];
        };
        PaginatedMessageList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Message"][];
        };
        PaginatedNotificationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Notification"][];
        };
        PaginatedOfferRowList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["OfferRow"][];
        };
        PatchedDocumentsRequest: {
            /**
             * ID document
             * Format: binary
             */
            document_file?: string;
            /** Format: binary */
            bank_certificate?: string;
        };
        PatchedListingRequest: {
            category?: number;
            /** Name */
            title?: string;
            description?: string;
            condition?: components["schemas"]["ConditionEnum"];
            /** Category fields */
            attributes?: unknown;
            city?: string;
            pickup_address?: string;
            /** Original? */
            is_original?: boolean;
            terms_accepted?: boolean;
        };
        PatchedUserRequest: {
            /** Name */
            first_name?: string;
            last_name?: string;
            email?: string;
            /** Format: binary */
            photo?: string;
            language?: components["schemas"]["LanguageEnum"];
            /** ID type */
            document_type?: components["schemas"]["DocumentTypeEnum"] | components["schemas"]["BlankEnum"];
            /** ID number */
            document_number?: string;
        };
        PayRequest: {
            /** Format: decimal */
            amount: string;
            /** Format: date */
            paid_at?: string | null;
            reference?: string;
            /** Format: binary */
            receipt?: string;
        };
        Period: {
            created: number;
            offered: number;
            accepted: number;
            /** Format: double */
            acceptance_rate: number | null;
            paid_count: number;
            /** Format: decimal */
            paid_total: string;
            /** Format: decimal */
            average_paid: string | null;
            /** Format: decimal */
            offered_total: string;
            /** Format: double */
            hours_to_offer: number | null;
        };
        /**
         * @description * `seller` - seller
         *     * `platform` - platform
         * @enum {string}
         */
        PickupPickupByEnum: "seller" | "platform";
        PickupRequest: {
            pickup_by: components["schemas"]["PickupPickupByEnum"];
            /** Format: date */
            pickup_date?: string | null;
            notes?: string;
        };
        /** @description Cuántas publicaciones esperan una acción del operador. */
        Queue: {
            unoffered: number;
            countered: number;
            pickups_today: number;
            unpaid: number;
            oldest_waiting_days: number | null;
        };
        ReasonRequest: {
            reason?: string;
        };
        /**
         * @description * `seller` - Seller
         *     * `operator` - Operator
         * @enum {string}
         */
        RoleEnum: "seller" | "operator";
        Seller: {
            id: number;
            name: string;
        };
        SellerRequest: {
            id: number;
            name: string;
        };
        /** @description Lo que ve el vendedor arriba de sus publicaciones. */
        SellerSummary: {
            /** Format: decimal */
            paid_total: string;
            /** Format: decimal */
            pending_total: string;
            paid_count: number;
            in_progress: number;
            currency: string;
        };
        SubscribeRequest: {
            /** Format: email */
            email: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        UnsubscribeRequest: {
            /** Format: uuid */
            token: string;
        };
        User: {
            readonly id: number;
            readonly phone: string;
            /** Name */
            first_name?: string;
            last_name?: string;
            email?: string;
            /** Format: uri */
            photo?: string | null;
            language?: components["schemas"]["LanguageEnum"];
            readonly role: components["schemas"]["RoleEnum"];
            /** ID type */
            document_type?: components["schemas"]["DocumentTypeEnum"] | components["schemas"]["BlankEnum"];
            /** ID number */
            document_number?: string;
            readonly has_document_file: boolean;
            readonly has_bank_certificate: boolean;
            /** @description Datos mínimos para que la plataforma pueda pagarle al vendedor. */
            readonly profile_complete: boolean;
            /** Format: date-time */
            readonly date_joined: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_otp_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OtpRequestRequest"];
                "multipart/form-data": components["schemas"]["OtpRequestRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpIssued"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpResendTooSoon"];
                };
            };
        };
    };
    auth_otp_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OtpVerifyRequest"];
                "multipart/form-data": components["schemas"]["OtpVerifyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    listings_list: {
        parameters: {
            query?: {
                /** @description Código de la categoría */
                category?: string;
                city?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Busca en nombre, descripción y vendedor */
                q?: string;
                /** @description Cola del operador */
                queue?: "countered" | "pickups_today" | "unoffered" | "unpaid";
                /** @description Uno o varios estados separados por coma */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListingList"];
                };
            };
        };
    };
    listings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ListingRequest"];
                "multipart/form-data": components["schemas"]["ListingRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_messages_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
            };
            header?: never;
            path: {
                listing_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMessageList"];
                };
            };
        };
    };
    listings_messages_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MessageRequest"];
                "multipart/form-data": components["schemas"]["MessageRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    listings_messages_attachment_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                listing_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archivo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listings_messages_read_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkRead"];
                };
            };
        };
    };
    listings_retrieve: {
        parameters: {
            query?: {
                /** @description Código de la categoría */
                category?: string;
                city?: string;
                /** @description Busca en nombre, descripción y vendedor */
                q?: string;
                /** @description Cola del operador */
                queue?: "countered" | "pickups_today" | "unoffered" | "unpaid";
                /** @description Uno o varios estados separados por coma */
                status?: string;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this listing. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this listing. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedListingRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedListingRequest"];
                "multipart/form-data": components["schemas"]["PatchedListingRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_accept_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this listing. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_accept_counter_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this listing. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this listing. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ReasonRequest"];
                "multipart/form-data": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_complete_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this listing. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_counter_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this listing. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CounterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CounterRequest"];
                "multipart/form-data": components["schemas"]["CounterRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_events_list: {
        parameters: {
            query?: {
                /** @description Código de la categoría */
                category?: string;
                city?: string;
                /** @description Busca en nombre, descripción y vendedor */
                q?: string;
                /** @description Cola del operador */
                queue?: "countered" | "pickups_today" | "unoffered" | "unpaid";
                /** @description Uno o varios estados separados por coma */
                status?: string;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this listing. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingEvent"][];
                };
            };
        };
    };
    listings_images_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this listing. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ListingImageRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingImage"];
                };
            };
        };
    };
    listings_images_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this listing. */
                id: number;
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listings_offer_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this listing. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OfferRequest"];
                "multipart/form-data": components["schemas"]["OfferRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_pay_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this listing. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PayRequest"];
                "multipart/form-data": components["schemas"]["PayRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_pickup_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this listing. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PickupRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PickupRequest"];
                "multipart/form-data": components["schemas"]["PickupRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_receipt_retrieve: {
        parameters: {
            query?: {
                /** @description Código de la categoría */
                category?: string;
                city?: string;
                /** @description Busca en nombre, descripción y vendedor */
                q?: string;
                /** @description Cola del operador */
                queue?: "countered" | "pickups_today" | "unoffered" | "unpaid";
                /** @description Uno o varios estados separados por coma */
                status?: string;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this listing. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archivo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listings_reject_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this listing. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ReasonRequest"];
                "multipart/form-data": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_dashboard_retrieve: {
        parameters: {
            query?: {
                /** @description Código de la categoría */
                category?: string;
                city?: string;
                /** @description Busca en nombre, descripción y vendedor */
                q?: string;
                /** @description Cola del operador */
                queue?: "countered" | "pickups_today" | "unoffered" | "unpaid";
                /** @description Uno o varios estados separados por coma */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    listings_offers_list: {
        parameters: {
            query?: {
                /** @description Código de la categoría */
                category?: string;
                city?: string;
                /** @description Columna de la tabla de ofertas, con - para descendente */
                ordering?: "city" | "created_at" | "offer_amount" | "offered_at" | "paid_amount" | "status" | "title";
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Busca en nombre, descripción y vendedor */
                q?: string;
                /** @description Cola del operador */
                queue?: "countered" | "pickups_today" | "unoffered" | "unpaid";
                /** @description Uno o varios estados separados por coma */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedOfferRowList"];
                };
            };
        };
    };
    listings_offers_export_retrieve: {
        parameters: {
            query?: {
                /** @description Código de la categoría */
                category?: string;
                city?: string;
                /** @description Columna de la tabla de ofertas, con - para descendente */
                ordering?: "city" | "created_at" | "offer_amount" | "offered_at" | "paid_amount" | "status" | "title";
                /** @description Busca en nombre, descripción y vendedor */
                q?: string;
                /** @description Cola del operador */
                queue?: "countered" | "pickups_today" | "unoffered" | "unpaid";
                /** @description Uno o varios estados separados por coma */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listings_stats_retrieve: {
        parameters: {
            query?: {
                /** @description Código de la categoría */
                category?: string;
                city?: string;
                /** @description Busca en nombre, descripción y vendedor */
                q?: string;
                /** @description Cola del operador */
                queue?: "countered" | "pickups_today" | "unoffered" | "unpaid";
                /** @description Uno o varios estados separados por coma */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingStats"];
                };
            };
        };
    };
    listings_summary_retrieve: {
        parameters: {
            query?: {
                /** @description Código de la categoría */
                category?: string;
                city?: string;
                /** @description Busca en nombre, descripción y vendedor */
                q?: string;
                /** @description Cola del operador */
                queue?: "countered" | "pickups_today" | "unoffered" | "unpaid";
                /** @description Uno o varios estados separados por coma */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SellerSummary"];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    me_documents_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedDocumentsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    me_documents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archivo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    newsletter_subscribe_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SubscribeRequest"];
                "multipart/form-data": components["schemas"]["SubscribeRequest"];
            };
        };
        responses: {
            /** @description Recibido */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    newsletter_unsubscribe_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnsubscribeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UnsubscribeRequest"];
                "multipart/form-data": components["schemas"]["UnsubscribeRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    notifications_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Solo las no vistas */
                unseen?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNotificationList"];
                };
            };
        };
    };
    notifications_seen_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this notification. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsSeen"];
                };
            };
        };
    };
    notifications_seen_all_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsSeen"];
                };
            };
        };
    };
    notifications_unseen_count_retrieve: {
        parameters: {
            query?: {
                /** @description Solo las no vistas */
                unseen?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationCount"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_documents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archivo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
