# Generated by Django 5.2.17 on 2026-09-19 08:35

import apps.accounts.files
import apps.accounts.managers
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='teléfono')),
                ('first_name', models.CharField(blank=True, max_length=80, verbose_name='nombre')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='apellido')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('photo', models.ImageField(blank=True, upload_to=apps.accounts.files.user_photo_path, verbose_name='foto')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=2, verbose_name='idioma')),
                ('role', models.CharField(choices=[('seller', 'Vendedor'), ('operator', 'Operador')], default='seller', max_length=10, verbose_name='rol')),
                ('document_type', models.CharField(blank=True, choices=[('national_id', 'Documento nacional'), ('foreign_id', 'Documento de extranjería'), ('passport', 'Pasaporte')], max_length=20, verbose_name='tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=30, verbose_name='número de documento')),
                ('document_file', models.FileField(blank=True, storage=apps.accounts.files.private_storage, upload_to=apps.accounts.files.user_document_path, validators=[apps.accounts.files.validate_private_file], verbose_name='documento')),
                ('bank_certificate', models.FileField(blank=True, storage=apps.accounts.files.private_storage, upload_to=apps.accounts.files.user_document_path, validators=[apps.accounts.files.validate_private_file], verbose_name='certificado bancario')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
