# Generated by Django 5.2.17 on 2026-09-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='en', max_length=2, verbose_name='idioma'),
        ),
    ]
