/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as AppCuentaRouteImport } from './routes/_app/cuenta'
import { Route as DevUiRouteImport } from './routes/dev.ui'
import { Route as NewsletterBajaRouteImport } from './routes/newsletter.baja'
import { Route as AppPublicacionesIndexRouteImport } from './routes/_app/publicaciones/index'
import { Route as AppPublicacionesIdRouteImport } from './routes/_app/publicaciones/$id'
import { Route as AppPublicacionesNuevaRouteImport } from './routes/_app/publicaciones/nueva'
import { Route as AppPublicacionesIdEditarRouteImport } from './routes/_app/publicaciones/$id_.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCuentaRoute = AppCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AppRoute,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterBajaRoute = NewsletterBajaRouteImport.update({
  id: '/newsletter/baja',
  path: '/newsletter/baja',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPublicacionesIndexRoute = AppPublicacionesIndexRouteImport.update({
  id: '/publicaciones/',
  path: '/publicaciones/',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicacionesIdRoute = AppPublicacionesIdRouteImport.update({
  id: '/publicaciones/$id',
  path: '/publicaciones/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicacionesNuevaRoute = AppPublicacionesNuevaRouteImport.update({
  id: '/publicaciones/nueva',
  path: '/publicaciones/nueva',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicacionesIdEditarRoute =
  AppPublicacionesIdEditarRouteImport.update({
    id: '/publicaciones/$id_/editar',
    path: '/publicaciones/$id/editar',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/terminos': typeof TerminosRoute
  '/cuenta': typeof AppCuentaRoute
  '/dev/ui': typeof DevUiRoute
  '/newsletter/baja': typeof NewsletterBajaRoute
  '/publicaciones/$id': typeof AppPublicacionesIdRoute
  '/publicaciones/nueva': typeof AppPublicacionesNuevaRoute
  '/publicaciones/': typeof AppPublicacionesIndexRoute
  '/publicaciones/$id/editar': typeof AppPublicacionesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/terminos': typeof TerminosRoute
  '/cuenta': typeof AppCuentaRoute
  '/dev/ui': typeof DevUiRoute
  '/newsletter/baja': typeof NewsletterBajaRoute
  '/publicaciones/$id': typeof AppPublicacionesIdRoute
  '/publicaciones/nueva': typeof AppPublicacionesNuevaRoute
  '/publicaciones': typeof AppPublicacionesIndexRoute
  '/publicaciones/$id/editar': typeof AppPublicacionesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/terminos': typeof TerminosRoute
  '/_app/cuenta': typeof AppCuentaRoute
  '/dev/ui': typeof DevUiRoute
  '/newsletter/baja': typeof NewsletterBajaRoute
  '/_app/publicaciones/$id': typeof AppPublicacionesIdRoute
  '/_app/publicaciones/nueva': typeof AppPublicacionesNuevaRoute
  '/_app/publicaciones/': typeof AppPublicacionesIndexRoute
  '/_app/publicaciones/$id_/editar': typeof AppPublicacionesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/terminos'
    | '/cuenta'
    | '/dev/ui'
    | '/newsletter/baja'
    | '/publicaciones/$id'
    | '/publicaciones/nueva'
    | '/publicaciones/'
    | '/publicaciones/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/terminos'
    | '/cuenta'
    | '/dev/ui'
    | '/newsletter/baja'
    | '/publicaciones/$id'
    | '/publicaciones/nueva'
    | '/publicaciones'
    | '/publicaciones/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/entrar'
    | '/terminos'
    | '/_app/cuenta'
    | '/dev/ui'
    | '/newsletter/baja'
    | '/_app/publicaciones/$id'
    | '/_app/publicaciones/nueva'
    | '/_app/publicaciones/'
    | '/_app/publicaciones/$id_/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  TerminosRoute: typeof TerminosRoute
  DevUiRoute: typeof DevUiRoute
  NewsletterBajaRoute: typeof NewsletterBajaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/cuenta': {
      id: '/_app/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AppCuentaRouteImport
      parentRoute: typeof AppRoute
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/baja': {
      id: '/newsletter/baja'
      path: '/newsletter/baja'
      fullPath: '/newsletter/baja'
      preLoaderRoute: typeof NewsletterBajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/publicaciones/': {
      id: '/_app/publicaciones/'
      path: '/publicaciones'
      fullPath: '/publicaciones/'
      preLoaderRoute: typeof AppPublicacionesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publicaciones/$id': {
      id: '/_app/publicaciones/$id'
      path: '/publicaciones/$id'
      fullPath: '/publicaciones/$id'
      preLoaderRoute: typeof AppPublicacionesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publicaciones/nueva': {
      id: '/_app/publicaciones/nueva'
      path: '/publicaciones/nueva'
      fullPath: '/publicaciones/nueva'
      preLoaderRoute: typeof AppPublicacionesNuevaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publicaciones/$id_/editar': {
      id: '/_app/publicaciones/$id_/editar'
      path: '/publicaciones/$id/editar'
      fullPath: '/publicaciones/$id/editar'
      preLoaderRoute: typeof AppPublicacionesIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCuentaRoute: typeof AppCuentaRoute
  AppPublicacionesIdRoute: typeof AppPublicacionesIdRoute
  AppPublicacionesNuevaRoute: typeof AppPublicacionesNuevaRoute
  AppPublicacionesIndexRoute: typeof AppPublicacionesIndexRoute
  AppPublicacionesIdEditarRoute: typeof AppPublicacionesIdEditarRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCuentaRoute: AppCuentaRoute,
  AppPublicacionesIdRoute: AppPublicacionesIdRoute,
  AppPublicacionesNuevaRoute: AppPublicacionesNuevaRoute,
  AppPublicacionesIndexRoute: AppPublicacionesIndexRoute,
  AppPublicacionesIdEditarRoute: AppPublicacionesIdEditarRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EntrarRoute: EntrarRoute,
  TerminosRoute: TerminosRoute,
  DevUiRoute: DevUiRoute,
  NewsletterBajaRoute: NewsletterBajaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
