# Generated by Django 5.2.17 on 2026-09-19 09:16

import apps.accounts.files
import apps.chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_platform', models.BooleanField(verbose_name='enviado por la plataforma')),
                ('text', models.TextField(blank=True, max_length=4000, verbose_name='texto')),
                ('attachment', models.FileField(blank=True, storage=apps.accounts.files.private_storage, upload_to=apps.chat.models.attachment_path, validators=[apps.chat.models.validate_attachment], verbose_name='adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='leído')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='listings.listing')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['listing', 'from_platform', 'read_at'], name='chat_messag_listing_266663_idx')],
            },
        ),
    ]
